# Zakończenie

<br>

Teoria współczesnych systemów monetarnych znana bardziej jako nowoczesna teoria monetarna powstała już trzy dekady temu, a opiera się na dokonaniach ekonomistów takiego kalibru jak J.M. Keynes i M. Kalecki. W dużym stopniu stanowi więc współczesną interpretację dawno istniejących teorii, z tym że dostosowaną do współczesnych gospodarek w szczególności tych z rozwiniętymi rynkami finansowymi. Jej siłą i głównym wkładem w teorię ekonomii, oprócz aktualności, jest szczegółowa analiza relacji między bankiem centralnym a skarbem państwa. MMT udowadnia, na gruncie teoretycznym, przewagę polityki budżetowej nad pieniężną w sterowaniu gospodarką. W ten sposób powraca w pewnym stopniu do teorii dominujących w latach pięćdziesiątych i sześćdziesiątych -- kładących nacisk na całkowity popyt. Niestety, od lat siedemdziesiątych największą popularnością cieszą się teorie według których to po stronie podaży stoją ograniczenia wzrostu gospodarczego. Ostatnie dwa kryzysy -- globalny kryzys finansowy oraz obecny kryzys spowodowany pandemią COVID19 spowodowały, że znowu zaczyna się uważać, że główną barierą rozwoju jest niedostateczny popyt. Niespotykane w historii pakiety pomocowe realizowane zarówno przez banki centralne jak i rządy państw nie spowodowały galopującej inflacji obalając tym samym dominujące dotychczas teorie ekonomiczne. Otworzyło to przestrzeń, którą stara się zagospodarować MMT.

O wartości teorii świadczy jej zdolność do spójnego wyjaśniania rzeczywistości. Niestety słabością MMT jest koncentracja na wyjaśnianiu rzeczywistości amerykańskiej. Dlatego celem prac, których zwieńczeniem są monografia naukowa oraz ta strona, było pokazanie przydatności MMT w kraju tak różnym od USA. Mam nadzieję, że udało mi się przekonać osoby czytające, iż nowoczesna teoria monetarna może być skutecznie wykorzystywana do wyjaśniania zjawisk gospodarczych w Polsce. System bankowy, Narodowy Bank Polski oraz skarb państwa funkcjonują tak, jak to opisuje MMT. To banki komercyjne kreują 80% pieniądza w gospodarce, NBP kontroluje stopy procentowe i ściśle współpracuje z ministerstwem finansów a wydatki publiczne dostarczają nowy pieniądz i działają w kierunku obniżenia stóp procentowych. Występują też istotne zjawiska nie uwzględnione do tej pory w literaturze MMT. Nadmiar pieniądza w sektorze bankowym w Polsce bierze się z napływu walut obcych przez co NBP nie musiał skupować skarbowych papierów wartościowych. Okazało się, że polityka podatkowa, mimo tak nowatorskiego spojrzeniu MMT na rolę podatków, stanowi w dużym stopniu białą plamę w tej teorii. Program gwarancji zatrudnienia, tak ważny automatyczny stabilizator koniunktury, może być obecnie dość łatwo wdrożony. Problemem jest jednak dość duża ogólnikowość tej propozycji i niewielkie doświadczenia z dotychczasowych prób jego wdrożenia. W efekcie może dojść do prób nadużyć w postaci obniżania płac pracowników etatowych administracji publicznej poprzez ich sztuczne przenoszenie do programu gwarancji zatrudnienia. Oznacza to konieczność wprowadzenia wpierw programu w postaci pilotażowej.

Istnieją też istotne ograniczenia instytucjonalne dotyczące możliwości skutecznego wdrożenia w Polsce zaleceń formułowanych przez tę teorię. Dotyczą one przede wszystkim zapisów konstytucyjnych i traktatowych ograniczających wielkość deficytu i długu publicznego. Bariery te mogą jednak zostać zniesione przy wystarczającej woli politycznej. Nota bene MMT uwzględnia istotną realną rolę polityki, zwłaszcza w przypadku banków centralnych, wykazując, że ich niezależność jest znacznie mniejsza niż to deklarują ekonomiści głównego nurtu.

Kryzys spowodowany COVID19 stanowi naturalny eksperyment, który wskazuje na prawdziwość i przydatność tej teorii. Natomiast na pytanie, czy udało mi się wystarczająco wyjaśnić czym jest MMT czytelnik lub czytelniczka musi odpowiedzieć sobie sam.
