# Bibliografia
<br>
Alcaraz, Carlo, Stijn Claessens, Gabriel Cuadra, David Marqués-Ibáñez, i Horacio Sapriza. 2019. Whatever It Takes: What’s the Impact of a Major Nonconventional Monetary Policy Intervention? 2249. European Central Bank.

Aliber, Robert Z., i Charles P. Kindleberger. 2017. Manias, Panics, and Crashes: A History of Financial Crises, Seventh Edition. 7th Edition. Palgrave Macmillan.

Anon. b.d. „Narodowy Bank Polski - Internetowy Serwis Informacyjny”. Pobrano 29 sierpień 2019 (https://www.nbp.pl/home.aspx?f=/statystyka/pieniezna_i_bankowa/krf.html).

Arendt, Łukasz. 2005. „Próba Oszacowania NAIRU Dla Polski”. Gospodarka Narodowa 200(5–6):1–23. doi: 10.33119/GN/101501.

Augustyński, Iwo. 2016. „Skutki podniesienia kwoty wolnej od podatku od dochodów osobistych”. Gospodarka Narodowa (1):55–71.

Ball, Laurence, J. Bradford DeLong, i Lawrence H. Summers. 2017. „Fiscal Policy and Full Employment”. S. 85–106 w Confronting Policy Challenges of the Great Recession: Lessons for Macroeconomic Policy, zredagowane przez E. Alvi. W.E. Upjohn Institute.

Bankier. 2021. „Goldman Sachs: wysoka inflacja w krajach Europy Środkowej ma charakter przejściowy”. Bankier.pl. Pobrano 23 sierpień 2021 (https://www.bankier.pl/wiadomosc/Goldman-Sachs-wysoka-inflacja-w-krajach-Europy-Srodkowej-ma-charakter-przejsciowy-8169893.html).

Bednarczyk, Jan L. 2013. „Hipoteza inflacji neutralnej a NAIRU”. Acta Universitatis Lodziensis. Folia Oeconomica 281 Gospodarka w okresie globalnego kryzysu:41–55.

Bezemer, Dirk. 2009. No one saw this coming. Understanding financial crisis through accounting models. Research Report. 09002. University of Groningen, Research Insti-tute SOM (Systems, Organisations and Management).

Bhaduri, Amit. 2015. „Aktualność teorii zarządzania popytem w świecie zglobalizowanym”. s. 251–64 w Globalny kryzys gospodarczy po roku 2008. Perspektywa postkeynesowska. Warszawa: Instytut Studiów Zaawansowanych.

Biegun, Krzysztof. 2017. „Ocena stabilizacyjnej roli zmian kursu walutowego w Polsce w kontekście potencjalnego członkostwa w strefie euro”. Studia i Prace WNEiZ US (47/1):81–93.

Blanchard, Oliver. 2011. Makroekonomia. Warszawa: Wydawnictwo Wolters Kluwer.

Blanchard, Olivier J., i Lawrence H. Summers. 1986. Hysteresis and the European Unem-ployment Problem. 1950. National Bureau of Economic Research, Inc.

Blanchard, Olivier J., i Lawrence H. Summers. 1987. „Hysteresis in Unemployment”. European Economic Review 31(1–2):288–95.

Blanchard, Olivier J., i Lawrence H. Summers. 1988. „Beyond the Natural Rate Hypothesis”. American Economic Review 78(2):182–87.

Bludnik, Izabela. 2015. Postkeynesizm. Teoria endogenicznej kreacji pieniądza. Poznań: Wydawnictwo Uniwersytetu Ekonomicznego w Poznaniu.

Bludnik, Izabela. 2018. „Postkeynesowskie teorie endogenicznej podaży pieniądza”. Ruch Prawniczy, Ekonomiczny i Socjologiczny 80(2):159–70. doi: 10.14746/rpeis.2018.80.2.12.

Bludnik, Izabela, i Marek Ratajczak. 2017. „Teoria obiegu pieniężnego w warunkach finansjalizacji”. Studia Ekonomiczne (2):239–59.

Boettke, Peter J. 2018. „Hayek on Market Theory and the Price System”. S. 77–118 w F. A. Hayek: Economics, Political Economy and Social Philosophy, Great Thinkers in Economics, zredagowane przez P. J. Boettke. London: Palgrave Macmillan UK.

Bonizzi, Bruno. 2017. „An alternative post-Keynesian framework for understanding capital flows to emerging markets”. Journal of Economic Issues 51(1):137–62.

Bonizzi, Bruno, Annina Kaltenbrunner, i Jo Michell. 2019. „Monetary sovereignty is a spec-trum: modern monetary theory and developing countries”. real-world economics re-view 89:46.

Botta, Alberto, Eugenio Caverzasi, i Daniele Tori. 2015. Financial-Real Side Interactions in an Extended Monetary Circuit with Shadow Banking: Loving or Dangerous Hugs? 14069. University of Greenwich, Greenwich Political Economy Research Centre.

Brady, Gordon L. 2020. „Modern Monetary Theory: Some Additional Dimensions”. Atlantic Economic Journal 48(1):1–9. doi: 10.1007/s11293-020-09654-6.

Brzeziński, Bogumił. 2017. Prawo podatkowe. Zagadnienia teorii i praktyki. I. Toruń: TNOiK – Towarzystwo Naukowe Organizacji i Kierowania. „Dom Organizatora”.

Bukowski, Sławomir I. 2007. Unia monetarna. Teoria i polityka. Warszawa: Difin.

Burdzicka, Monika, Irmina Cerling, Jolanta Gałkowska, Monika Grabani, Katarzyna Kach-niarz, Marta Kaźmierska, Małgorzata Buba, Małgorzata Kordas, Piotr Krawczyk, Daniel Michalik, Anna Milewska, Anita Perzyna, Karol Sawicki, Leokadia Szczałuba, Ewa Szczerbińska, i Zofia Wnuk. 2019. Rachunki narodowe według sektorów i podsektorów instytucjonalnych 2014-2017. Warszawa: Główny Urząd Statystyczny.

Caverzasi, Eugenio, i Antoine Godin. 2013. Stock-flow Consistent Modeling through the Ages. Economics Working Paper Archive. wp_745. Levy Economics Institute.

Caverzasi, Eugenio, i Antoine Godin. 2015. „Post-Keynesian stock-flow-consistent model-ling: a survey”. Cambridge Journal of Economics 39(1):157–87. doi: 10.1093/cje/beu021.

Cochrane, John H. 2020. „The Grumpy Economist: Magical monetary theory full review”. The Grumpy Economist. Pobrano 12 październik 2020 (https://johnhcochrane.blogspot.com/2020/07/magical-monetary-theory-full-review.html).

Copeland, Morris A. 1949. „Social Accounting for Moneyflows”. The Accounting Review 24(3):254–64.

Coy, Peter. 2021. „Summers and Krugman Debate Stimulus. Here’s a Blow-by-Blow Account”. Bloomberg.Com, luty 12.

DeLong, Brad. 2019. „By Popular Demand: What Is “Modern Monetary Theory”?” Grasping Reality by Brad DeLong. Pobrano 15 czerwiec 2021 (https://www.bradford-delong.com/2019/01/what-is-modern-monetary-theory.html).

Dos Santos, Claudio H. Dos. 2006. „Keynesian Theorising during Hard Times: Stock-Flow Consistent Models as an Unexplored ‘Frontier’ of Keynesian Macroeconomics”. Cambridge Journal of Economics 30(4):541–65. doi: 10.1093/cje/bei069.

Dow, Sheila C. 1985. Macroeconomic Thought: A Methodological Approach. Oxford, UK; New York, NY, USA: B. Blackwell.

Drenik, Andres, i Diego Perez. 2020. Domestic Price Dollarization in Emerging Economies. 27647. National Bureau of Economic Research, Inc.

Driessen, Grant A., i Jane G. Gravelle. 2019. Deficit Financing, the Debt, and “Modern Monetary Theory”. R45976. Congressional Research Service.
Duc, Louis Bê, i Gwenaël Le Breton. 2009. Flow-of-funds analysis at the ECB – framework and applications. Occasional Paper Series. 105. European Central Bank.

Epstein, Gerald. 2019. What’s Wrong with Modern Money Theory?: A Policy Critique. Springer.

Epstein, Gerald. 2020. „The Empirical and Institutional Limits of Modern Money Theory”. Review of Radical Political Economics 0486613420912464. doi: 10.1177/0486613420912464.

ESA 2010. 2013. European system of accounts - ESA 2010. Luxembourg: Eurostat.

European Commission i Directorate-General for Economic and Financial Affairs. 2019. Vade Mecum on the Stability and Growth Pact: 2019 Edition.

Fiedor, Bogusław. 2013. „Uwagi o potrzebie równowagi metodologicznej w ekonomii”. Studia Ekonomiczne (1):101–18.

Friedman, Milton. 1948. „A Monetary and Fiscal Framework for Economic Stability”. American Economic Review (38):245264.

Friedman, Milton. 1966. Essays in Positive Economics. University of Chicago Press.

Fullwiler, Scott. 2015. „Replacing the Budget Constraint with an Inflation Constraint”. New Economic Perspectives. Pobrano 2 wrzesień 2020 (http://neweconomicperspectives.org/2015/01/replacing-budget-constraint-inflation-constraint.html).

Fullwiler, Scott, Stephanie Kelton, i Larry Randall Wray. 2012. „“Modern  money  theory:  A  response  to  critics”. Modern Monetary Theory: A Debate (279):17–26.

Galbraith, James K. 2019. „Modern Monetary Realism | by James K. Galbraith”. Project Syndicate. Pobrano 28 lipiec 2021
(https://www.project-syndicate.org/commentary/modern-monetary-theory-opponents-misunderstanding-by-james-k--galbraith-2019-03).

Godin, Antoine. 2012a. Guaranteed Green Jobs: Sustainable Full Employment. wp_722. Levy Economics Institute.

Godin, Antoine. 2012b. Job Guarantee: A Structuralist Perspective. 016. University of Pa-via, Department of Economics and Management.

Godley, Wynne, i Francis Cripps. 1983. Macroeconomics. Oxford; New York: Oxford Uni-versity Press.

Godley, Wynne, i M. Lavoie. 2007. Monetary Economics: An Integrated Approach to Credit, Money, Income, Production and Wealth. Houndmills, Basingstoke, Hampshire; New York: Palgrave Macmillan.

Godley, Wynne, i Marc Lavoie. 2006. Prolegomena to Realistic Monetary Macroeconomics: A Theory of Intelligible Sequences. Economics Working Paper Archive. wp_441. Levy Economics Institute.

Graeber, David. 2019. Dług. Pierwsze pięć tysięcy lat. Warszawa: Wydawnictwo Krytyki Politycznej.

Guichard, Stéphanie, i Elena Rusticelli. 2011. „Reassessing the NAIRUs after the Crisis”. doi: https://doi.org/10.1787/5kg0kp712f6l-en.

Juniper, James, Timothy P. Sharpe, i Martin J. Watts. 2014. „Modern monetary theory: con-tributions and critics”. Journal of Post Keynesian Economics 37(2):281–307. doi: 10.2753/PKE0160-3477370205.2015.11082991.

Kaboub, Fadhel. 2007. „ELR-led economic development: A plan for Tunisia”. Levy Institute Working Paper (499).

Kadmos, George, i Phillip O’Hara. 2000. „The Taxes-Drive-Money and Employer of Last Resort Approach to Government Policy”. Journal of Economic and Social Policy 5(1).

Kalecki, Michał. 1979. Kapitalizm: koniunktura i zatrudnienie. T. 1. Warszawa: Państwowe Wydawnictwo Ekonomiczne.

Kalecki, Michał. 1980. „Teoria dynamiki gospodarczej”. S. 215–47 w Kapitalizm: dynamika gospodarcza. T. 2, Dzieła. Państwowe Wydawnictwo Ekonomiczne.

Kąsek, Leszek, i Marek Lubiński. 2010. „Hyman Minsky - wczoraj i dziś”. Współczesna Ekonomia 4(nr 1):5–20.

Kelton, Stephanie. 2020. The Deficit Myth: Modern Monetary Theory and the Birth of the People’s Economy. New York: PublicAffairs.

Khalil, Saed, i Stephen Kinsella. 2011. Bad banks choking good banks: simulating balance sheet contagion. Working Paper. 201126. Geary Institute, University College Dublin.

King, J. E. 2001. „Comment on: George Kadmos & Phillip O’Hara - «The Taxes-Drive-Money and Employer of Last Resort Approach to Government Policy», Journal of Economic and Social Policy, vol. 5, no. 1, Summer 2000, pp. 1-22.” Journal of Eco-nomic and Social Policy 5(2).

Kinsella, Stephen. 2011. Words to the Wise: Stock Flow Consistent Modeling of Financial Instability. INET Research Notes. 19. Institute for New Economic Thinking (INET).

Kisiel, Michał. 2020. „Jak się pracuje w bankach. Sprzedaż «na siłę» ma się całkiem do-brze”. Bankier.pl. Pobrano 31 sierpień 2020 (https://www.bankier.pl/wiadomosc/Jak-sie-pracuje-w-bankach-Sprzedaz-na-sile-ma-sie-calkiem-dobrze-7949676.html).

Knakiewicz, Zenobia. 1984. „Aktualne aspekty teorii pieniądza G. F. Knappa”.

Knakiewicz, Zenobia. 1998. „Problemy kreacji pieniądza i regulacji obiegu pieniężnego”. Ruch Prawniczy, Ekonomiczny i Socjologiczny 3–4(60):163–79.

Kowalczyk, Zygmunt. 1978. Strumienie finansowe w gospodarce kapitalistycznej. Warszawa: PWN.

Krugman, Paul. 2019. „Opinion | Running on MMT (Wonkish)”. The New York Times, luty 25.

Lapavitsas, Costas, i Nicolás Aguila. 2020. „Modern Monetary Theory on Money, Sovereignty, and Policy: A Marxist Critique with Reference to the Eurozone and Greece”. Japanese Economy 46(4):300–326.

Lavoie, Marc. 2013. „The Monetary and Fiscal Nexus of Neo-Chartalism: A Friendly Critique”. Journal of Economic Issues 47(1):1–32. doi: 10.2753/JEI0021-3624470101.

Lavoie, Marc. 2014. Post-Keynesian Economics: New Foundations. Edward Elgar Publishing.

Lavoie, Marc. 2019. „Modern monetary theory and post-Keynesian economics”. real-world economics review (89):97–108.

Lawędziak, Bartosz. 2017. „Analiza mnożnika wydatków państwowych dla Polski w latach 2008-2013”. Studia Ekonomiczne 324:45–52.

Lerner, Abba. 1943. „Functional Finance and the Federal Debt”. Social Research 10(1):38–51.

Lerner, Abba. 2015. „Funkcjonalne finanse i dług publiczny”. S. 125–42 w Globalny kryzys gospodarczy po roku 2008. Perspektywa postkeynesowska., zredagowane przez K. Łaski i J. Osiatyński. Warszawa: Instytut Studiów Zaawansowanych.

Levrero, Enrico Sergio, Matteo Deleidi, i Francesca Iafrate. 2019. Public Investment Fiscal Multipliers: An Empirical Assessment For European Countries. 0247. Department of Economics - University Roma Tre.

Łaski, Kazimierz. 2011. „Strukturalne przyczyny kryzysu finansów publicznych w Unii Europejskiej oraz w Unii Gospodarczej i Walutowej”. Studia Ekonomiczne (1):7–18.

Łaski, Kazimierz. 2015. Wykłady z makroekonomii. Gospodarka kapitalistyczna bez bezrobocia. zredagowane przez W. Osiatyński. Warszawa: PTE.

Łaski, Kazimierz, Jerzy Osiatyński, i Jolanta Zięba. 2010. „Mnożnik wydatków państwo-wych i szacunki jego wielkości dla Polski”. Materiały i Studia (246).

Makrelov, Konstantin, Channing Arndt, Rob Davies, i Laurence Harris. 2019. „Balance sheet changes and the impact of financial sector risk-taking on fiscal multipliers”. Eco-nomic Modelling. doi: 10.1016/j.econmod.2019.08.006.

Mankiw, N. Gregory. 2020. „A Skeptic’s Guide to Modern Monetary Theory”. AEA Papers and Proceedings 110:141–44. doi: 10.1257/pandp.20201102.

Marchewka-Bartkowiak, Kamilla. 2013. „Konsekwencje zróżnicowania metodologii pomia-ru długu publicznego w Polsce”. Analizy BAS (11(100)):1–8.

Marczewski, Krzysztof. 2006. „Rachunki finansowe sektorów instytucjonalnych gospodarki jako narzędzia analizy makroekonomicznej”. Prace i Materiały Instytutu Rozwoju Gospodarczego / Szkoła Główna Handlowa (nr 78 Polityka stabilizacji, rozwoju i ła-du gospodarczego):138–66.

Mayhew, Anne. 2019. „The sleights of hand of MMT”. real-world economics review 129–37.

Mazurek-Chwiejczak, Małgorzata. 2016. „Wydajny fiskalnie system podatkowy - w poszukiwaniu modelowych rozwiązań”. Prace Naukowe Uniwersytetu Ekonomicznego we Wrocławiu (nr 451 Finanse publiczne):268–79. doi: 10.15611/pn.2016.451.22.

Mączyńska, Elżbieta. 2014. Ekonomia dla przyszłości. Fundamentalne problemy teorii ekonomii i praktyki gospodarczej. I. Warszawa: Polskie Towarzystwo Ekonomiczne.

McLeay, Michael, Amar Radia, i Ryland Thomas. 2014. „Money Creation in the Modern Economy”. Bank of England Quarterly Bulletin 54(1):14–27.

Michalczyk, Wawrzyniec. 2013a. „Determinanty poziomu realnego kursu złotego w dobie globalizacji i jego konsekwencje dla handlu zagranicznego”. Studia Ekonomiczne 129:117–26.

Michalczyk, Wawrzyniec. 2013b. „Uwarunkowania kursu złotego względem euro w per-spektywie przystąpienia do mechanizmu ERM2”. Finanse.

Michalczyk, Wawrzyniec. 2016. „Zależności między kursem złotego względem euro a wybranymi zmiennymi makroekonomicznymi w latach 2011-2015”. Prace Naukowe Uniwersytetu Ekonomicznego we Wrocławiu (448):193–205.

Minsky, Hyman P. 2008. Stabilizing an Unstable Economy. McGraw-Hill Professional.

Mitchell, William. 2017. „The Job Guarantee: A Superior Buffer Stock Option for Govern-ment Price Stabilisation”. S. 89–115 w The Job Guarantee and Modern Money Theo-ry: Realizing Keynes’s Labor Standard, zredagowane przez M. J. Murray i M. For-stater. Cham: Springer International Publishing.

Mitchell, William F. 1998. „The Buffer Stock Employment Model and the NAIRU: The Path to Full Employment”. Journal of Economic Issues 32(2):547–55.

Mitchell, William, i Joan Muysken. 2010. „Full Employment Abandoned: Shifting Sands and Policy Failures”. International Journal of Public Policy 5(4):295–313.

Mitchell, William, i L. Randall Wray. 2005. „In Defense of Employer of Last Resort: A Response to Malcolm Sawyer”. Journal of Economic Issues 39(1):235–44.

Mitchell, William, L. Randall Wray, i Martin Watts. 2019. Macroeconomics. Macmillan Education UK.

Mosler, Warren. 1997. „Full Employment and Price Stability”. Journal of Post Keynesian Economics 20(2):167–82.

Nawrot, Wioletta. 2009. „Teoria kryzysów finansowych Minsky’ego i jej odniesienie do współczesności”. Gospodarka Narodowa (10):49–70.

NBER. 1962. „The Flow-of Funds Approach to Social Accounting”. w NBER. Princeton University Press.

NBP. 2021. „Narodowy Bank Polski - Statystyka i Sprawozdawczość”. Pobrano 23 sierpień 2021 (https://www.nbp.pl/home.aspx?f=/statystyka/wskazniki/wykresy.html).

Newman, Patrick. 2020. „Modern Monetary Theory: An Austrian Interpretation of Recru-descent Keynesianism”. Atlantic Economic Journal 48(1):23–31. doi: 10.1007/s11293-020-09653-7.

Nikiforos, Michalis, i Gennaro Zezza. 2017. Stock-flow Consistent Macroeconomic Models: A Survey. wp_891. Levy Economics Institute.
OECD. 2017. Understanding Financial Accounts. OECD Publishing.

O’Hara, Phillip, i George Kadmos. 2001. „A Reply to King: Employer of Last Resort and Taxes-Drive-Money Revisited”. Journal of Economic and Social Policy 5(2).

Özyurt, Selin, i Simon CUEVA (TNK Economics). 2020. Twenty Years of Official Dollariza-tion in Ecuador: A Blessing or a Curse? 19795ea3-88a3-4f85-af90-a512b8ebe33b. Agence française de développement.

Palley, Thomas. 2019a. Macroeconomics vs Modern Money Theory: Some Unpleasant Keynesian Arithmetic. PKWP1910. Post Keynesian Economics Society (PKES).

Palley, Thomas. 2019b. What’s Wrong With Modern Money Theory (MMT): A Critical Pri-mer. 44–2019. IMK at the Hans Boeckler Foundation, Macroeconomic Policy Institute.

Phelps, Edmund S. 1994. Structural Slumps: The Modern Equilibrium Theory of Unemployment, Interest, and Assets. Harvard University Press.
Pissarides, Christopher A. 1992. „Loss of Skill During Unemployment and the Persistence of Employment Shocks”. The Quarterly Journal of Economics 107(4):1371–91.

Pošta, Vít. 2015. „Time-Varying NAIRU and Some of Its Determinants—A Semi-Structural Approach: Evidence from Eastern European Economies”. Eastern European Economics 53(2):149–65. doi: 10.1080/00128775.2015.1034058.

Prates, Daniela. 2020. „Beyond Modern Money Theory: A Post-Keynesian Approach to the Currency Hierarchy, Monetary Sovereignty, and Policy Space”. Review of Keynesian Economics 8(4):494–511. doi: https://doi.org/10.4337/roke.2020.04.03.

Ramsay, Tony. 2002. „The Jobs Guarantee: A Post Keynesian Analysis”. Journal of Post Keynesian Economics 25(2):273–91.

Reinhart, Carmen M., i Kenneth S. Rogoff. 2009. This Time Is Different: Eight Centuries of Financial Folly. Princeton University Press.

Reinhart, Carmen M., Kenneth S. Rogoff, i Miguel A. Savastano. 2003. Addicted to Dollars. 594. China Economics and Management Academy, Central University of Finance and Economics.

Rochon, Louis-Philippe. 2019. „MMT and TINA”. real-world economics review 89:156–66.

Rochon, Louis-Philippe, i Sergio Rossi. 2016. An Introduction to Macroeconomics: A Heterodox Approach to Economic Analysis. Edward Elgar Publishing.

Rochon, Louis-Philippe, i Matías Vernengo. 2003. „State money and the real world: or chartalism and its discontents”. Journal of Post Keynesian Economics 26(1):57–67. doi: 10.1080/01603477.2003.11051383.

Rochon, Louis-Phillipe, i Mario Seccareccia, red. 2003. Dollarization: Lessons from Europe for the Americas. London; New York: Routledge.
Rogoff, Kenneth. 2019. „Modern Monetary Nonsense | by Kenneth Rogoff”. Project Syndicate, marzec 4.

RPP. 2021. Raport o inflacji.

Salerno, Joe. 2019. „A Note From Dr. Joe Salerno on MMT”. Mises Institute. Pobrano 22 czerwiec 2021 (https://mises.org/power-market/note-dr-joe-salerno-mmt).

Santos, Claudio dos. 2004. A Stock-Flow Consistent General Framework for Formal Minskyan Analyses of Closed Economies. Economics Working Paper Archive. wp_403. Levy Economics Institute.

Santos, Claudio H. dos, i Gennaro Zezza. 2004. A Post-Keynesian Stock-Flow Consistent Macroeconomic Growth Model: Preliminary Results. Economics Working Paper Ar-chive. wp_402. Levy Economics Institute.

Sawyer, Malcolm. 2003. „Employer of Last Resort: Could It Deliver Full Employment and Price Stability?” Journal of Economic Issues 37(4):881–907.

Sawyer, Malcolm. 2005. „Employer of Last Resort: A Response to My Critics”. Journal of Economic Issues 39(1):256–64.

Sawyer, Malcolm. 2019. „Modern monetary theory: is there any added value?” real-world economics review 167–79.

Seccareccia, Mario. 2004a. „What type of full employment? A critical evaluation of “Government as the Employer of Last Resort” policy proposal”. Investigación económica 63(247):15–43.

Shiller, Robert J. 2019. „Modern Monetary Theory Makes Sense, Up to a Point”. The New York Times, marzec 29.

Silva, Antonio Carlos Macedo e, i Claudio H. Dos Santos. 2011. „Peering over the Edge of the Short Period? The Keynesian Roots of Stock-Flow Consistent Macroeconomic Models”. Cambridge Journal of Economics 35(1):105–24. doi: 10.1093/cje/bep083.

Skott, Peter. 2005. „Fairness as a Source of Hysteresis in Employment and Relative Wages”. Journal of Economic Behavior & Organization 57(3):305–31.

Skott, Peter. 2018. Challenges for Post-Keynesian Macroeconomics. 2018–03. University of Massachusetts Amherst, Department of Economics.

Skousen, Mark. 2020. „There’s Much Ruin in a Nation: An Analysis of Modern Monetary Theory”. Atlantic Economic Journal 48(1):11–21. doi: 10.1007/s11293-020-09651-9.

Sławiński, Andrzej. 2020. „Czego brakuje Modern Monetary Theory”. Rzeczpospolita, sierpień 30.

Socha, Jacek, i Wiktor Wojciechowski. 2004. „Koncepcja NAIRU, dezinflacja a druga fala bezrobocia w Polsce”. Bank i Kredyt (nr 3):4–15.

Socha, Mieczysław, i Urszula Sztanderska. 2002. Strukturalne podstawy bezrobocia w Pol-sce. 1.-dodruk wyd. Warszawa: PWN.

Stamatiou, Pavlos, i Chaido Dritsaki. 2019. „The Phillips Curve: Unemployment Dynamics and Nairu Estimates of Poland’s Economy”. Economia Internazionale / International Economics 72(3):281–312.

Stiglitz, Joseph. 1997. „Reflections on the Natural Rate Hypothesis”. Journal of Economic Perspectives 11(1):3–10.

Stockhammer, Engelbert. 2011. „Wage Norms, Capital Accumulation, and Unemployment: A Post-Keynesian View”. Oxford Review of Economic Policy 27(2):295–311.

Sulmicki, Paweł. 1978. Planowanie i zarządzanie gospodarcze. Warszawa: PWE.

Summers, Lawrence H. 2019. „The Left’s Embrace of Modern Monetary Theory Is a Recipe for Disaster”. Washington Post, kwiecień 5.
Sylla, Ndongo Samba. 2020. „Modern Monetary Theory in the Periphery”. Pobrano 6 sierpień 2021
(https://www.rosalux.de/en/news/id/41764/modern-monetary-theory-in-the-periphery).

Szewczyk, Nikodem. 2021. „Debata Krugman kontra Summers. Co mówi nam o stanie światowej ekonomii | Obserwator Finansowy: ekonomia, debata, Polska, świat”. Pobrano 16 lipiec 2021
(https://www.obserwatorfinansowy.pl/bez-kategorii/rotator/debata-krugman-kontra-summers-co-mowi-nam-o-stanie-swiatowej-ekonomii/).

Tcherneva, Pavlina R. 2007. What Are the Relative Macroeconomic Merits and Environmental Impacts of Direct Job Creation and Basic Income Guarantees? wp_517. Levy Economics Institute.

Tcherneva, Pavlina R. 2008. The Return of Fiscal Policy: Can the New Developments in the New Economic Consensus Be Reconciled with the Post-Keynesian View? wp_539. Levy Economics Institute.

Tcherneva, Pavlina R. 2012a. Beyond Full Employment: The Employer of Last Resort as an Institution for Change. wp_732. Levy Economics Institute.

Tcherneva, Pavlina R. 2012b. Inflationary and Distributional Effects of Alternative Fiscal Policies: An Augmented Minskyan-Kaleckian Model. wp_706. Levy Economics Institute.

Tcherneva, Pavlina R. 2013. Reorienting Fiscal Policy: A Critical Assessment of Fiscal Fine-Tuning. wp_772. Levy Economics Institute.

Tcherneva, Pavlina R. 2014a. Full Employment: The Road Not Taken. wp_789. Levy Economics Institute.

Tcherneva, Pavlina R. 2014b. The Social Enterprise Model for a Job Guarantee in the United States. 14–1. Levy Economics Institute.

Tcherneva, Pavlina R. 2017. Unemployment: The Silent Epidemic. wp_895. Levy Economics Institute.

Tcherneva, Pavlina R. 2018. The Job Guarantee: Design, Jobs, and Implementation. wp_902. Levy Economics Institute.

Tcherneva, Pavlina R. 2020. The Case for a Job Guarantee. 1st Edition. Cambridge: Polity.

Tcherneva, Pavlina R., i L. Randall Wray. 2007. Public Employment and Women: The Impact of Argentina’s Jefes Program on Female Heads of Poor Households. wp_519. Levy Economics Institute.

Tobin, James. 1980. Asset Accumulation and Economic Activity: Reflections on Contemporary Macroeconomic Theory. University of Chicago Press.

Tobin, James. 1982. Money and Finance in the Macro-Economic Process. Cowles Founda-tion Discussion Paper. 613R. Cowles Foundation for Research in Economics, Yale University.

Toporowski, Jan. 2005. Theories of Financial Disturbance: An Examination of Critical Theories of Finance from Adam Smith to the Present Day. Edward Elgar Publishing.

Toporowski, Jan. 2015. „Minsky’ego i Kaleckiego teoria pieniądza”. s. 151–64 w Globalny kryzys gospodarczy po roku 2008. Perspektywa postkeynesowska. Warszawa: Instytut Studiów Zaawansowanych.

Toporowski, Jan. 2019a. „Financial Control and the Employer of Last Resort”. Society Register 3(2). doi: 10.14746/sr.2019.3.2.03.

Toporowski, Jan. 2019b. „The political economy of modern money theory, from Brecht to Gaitskell”. real-world economics review 194–202.

Treeck, Till van. 2009. „A synthetic, stock-flow consistent macroeconomic model of «financialisation»”. Cambridge Journal of Economics 33(3):467–93.

Tweneboah, George, John Garchie Gatsi, i Michael Effah Asamoah. 2019. „Financial development and dollarization in Ghana: an empirical investigation” zredagowane przez M. Camarero. Cogent Economics & Finance 7(1):1663699. doi: 10.1080/23322039.2019.1663699.

Tymoczko, Izabela D. 2013. Analiza porównawcza systemów kursu walutowego. Narodowy Bank Polski. Departament Edukacji i Wydawnictw.

Tymoigne, Eric. 2014. Modern Money Theory and Interrelations between the Treasury and the Central Bank: The Case of the United States. 788. Levy Economics Institute.

Tymoigne, Eric, i L. Randall Wray. 2013. Modern Money Theory 101: A Reply to Critics. wp_778. Levy Economics Institute.

Umiński, Paweł. 2014. „Modern Monetary Theory Jako Alternatywne Podejście Do Pieniądza i Polityki Pieniężnej”. Acta Universitatis Lodziensis. Folia Oeconomica 1(299).

Winczewski, Damian. 2017. „Modern Monetary Theory a marksistowska krytyka ekonomii politycznej”. Praktyka Teoretyczna 3(25):136–75. doi: 10.14746/prt.2017.3.5.

Wojtyna, Andrzej. 2000. Ewolucja keynesizmu a główny nurt ekonomii. Warszawa: PWN.

Wojtyna, Andrzej. 2014. „Czy kryzys w teorii ekonomii jest głębszy niż w gospodarce?” s. 39–50 w Ekonomia dla przyszłości. Fundamentalne problemy teorii ekonomii i prak-tyki gospodarczej, zredagowane przez E. Mączyńska. Warszawa: PTE.

Wolański, Robert. 2016. System podatkowy w Polsce. 4. wyd. Warszawa: Wolters Kluwer.

Wray, L. Randall. 1993. „Abolish Taxes”. Journal of Post Keynesian Economics 15(4):621–25.

Wray, L. Randall. 2006. Understanding Policy in a Floating Rate Regime. SSRN Scholarly Paper. ID 1009577. Rochester, NY: Social Science Research Network. doi: 10.2139/ssrn.1009577.

Wray, L. Randall. 2007. Minsky’s Approach to Employment Policy and Poverty: Employer of Last Resort and the War on Poverty. SSRN Scholarly Paper. ID 1014163. Rochester, NY: Social Science Research Network.

Wray, L. Randall. 2014. Central Bank Independence. Myth and Misunderstanding. 791. Levy Economics Institute.

Wray, L. Randall. 2018. Functional Finance: A Comparison of the Evolution of the Positions of Hyman Minsky and Abba Lerner. wp_900. Levy Economics Institute.

Wray, L. Randall. 2020. „Sovereign Currency and Non-Sovereign Budgets: The Modern Money Theory Approach”. Public Budgeting & Finance. doi: 10.1111/pbaf.12251.

Wray, L. Randall, Flavia Dantas, Scott Fullwiler, Pavlina R. Tcherneva, i Stephanie A. Kel-ton. 2019. „Guaranteed Jobs through a Public Service Employment Programme for the United States”. S. 253–75 w Chapters. Edward Elgar Publishing.

Wray, L. Randall, Stephanie A. Kelton, Pavlina R. Tcherneva, Scott Fullwiler, i Flavia Dantas. 2018. Guaranteed Jobs through a Public Service Employment Program. 18–2. Levy Economics Institute.

Wray, Larry Randall. 2019. Nowoczesna teoria monetarna MMT: wprowadzenie do makroekonomii suwerennych systemów monetarnych. heterodox.

Zezza, Gennaro. 2019. „Editorial to the Special Issue on Empirical Stock–Flow Consistent Models”. European Journal of Economics and Economic Policies: Intervention 16(1):27–30. doi: 10.4337/ejeep.2019.01.03.

Zezza, Gennaro, i Francesco Zezza. 2019. „On the Design of Empirical Stock-Flow-Consistent Models”. (919).

Zygmuntowski, Jan J., Kirył Zach, i Krzysztof Hejduk. 2020. European Job Guarantee: Targeting the Triple Crises Facing Post-COVID Europe. SSRN Scholarly Paper. ID 3715344. Rochester, NY: Social Science Research Network. doi: 10.2139/ssrn.3715344.

